services:
  rosters_db:
    container_name: rosters_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rosters_db
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports: 
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: henry@henrywoodbury.com
      PGADMIN_DEFAULT_PASSWORD: massapoag

