services:
  rosters_db_service:
    container_name: rosters_db_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rosters_db
    ports:
      - "5432:5432"
